stages:
  - test and analysis

lint:
  stage: test and analysis
  image: registry.cafebazaar.ir:5000/infrastructure/kraken/common-images/golang:1.16.6
  script:
    - make fmt-check

husky:
  stage: test and analysis
  variables:
    NO_PROXY: ".security.sotoon.ir,.kise.cafebazaar.cloud,.kise-thr-nd-1.sotoon.cloud,.sotoon.ir,.cafebazaar.cloud"
  before_script:
    - wget --no-check-certificate https://huskyci-files.security.sotoon.ir/huskyci-client-bin
    - chmod +x huskyci-client-bin
  script:
    # todo consider checking for medium level errors
    - ./huskyci-client-bin -s bandit -s jake --level HIGH
  allow_failure: true
  timeout: 5m

test:
  stage: test and analysis
  image: registry.cafebazaar.ir:5000/infrastructure/kraken/common-images/golang:1.16.6
  script:
    - make test
