package routes

const (
	RouteAuthz   = "/authz"
	RouteHealthz = "/healthz"
	RouteMetrics = "/metrics"

	RoutePublicKeyCreate      = "/user/{user_uuid}/public-key"
	RoutePublicKeyGetOneByKey = "/public-key"
	RoutePublicKeyGetOne      = "/user/{user_uuid}/public-key/{public_key_uuid}"
	RoutePublicKeyGetAll      = "/user/{user_uuid}/public-key"
	RoutePublicKeyDelete      = "/user/{user_uuid}/public-key/{public_key_uuid}"

	RouteRoleCreate      = "/workspace/{workspace_uuid}/role"
	RouteRoleGetOne      = "/workspace/{workspace_uuid}/role/{role_uuid}"
	RouteRoleGetAll      = "/role"
	RouteRoleDelete      = "/workspace/{workspace_uuid}/role/{role_uuid}"
	RouteRoleGetAllUsers = "/workspace/{workspace_uuid}/role/{role_uuid}/user"
	RouteRoleGetAllRules = "/workspace/{workspace_uuid}/role/{role_uuid}/rule"
	RouteRoleAppendRule  = "/workspace/{workspace_uuid}/role/{role_uuid}/rule/{rule_uuid}"
	RouteRoleDropRule    = "/workspace/{workspace_uuid}/role/{role_uuid}/rule/{rule_uuid}"

	RouteRuleCreate      = "/workspace/{workspace_uuid}/rule"
	RouteRuleGetOne      = "/workspace/{workspace_uuid}/rule/{rule_uuid}"
	RouteRuleGetAll      = "/rule"
	RouteRuleDelete      = "/workspace/{workspace_uuid}/rule/{rule_uuid}"
	RouteRuleGetAllUsers = "/workspace/{workspace_uuid}/rule/{rule_uuid}/user"
	RouteRuleGetAllRoles = "/workspace/{workspace_uuid}/rule/{rule_uuid}/role"

	RouteServiceGetAll = "/service"
	RouteServiceGetOne = "/service/{name}"

	RouteUserInvite           = "/workspace/{workspace_uuid}/invite"
	RouteUserSetPassword      = "/accept-invitation/{user_invitation_token}"
	RouteUserCreate           = "/user"
	RouteUserSecretGet        = "/user/{user_uuid}/secret"
	RouteUserSecretPost       = "/user/{user_uuid}/secret"
	RouteUserGetOne           = "/user/{user_uuid}"
	RouteUserGetAll           = "/user"
	RouteUserDelete           = "/user/{user_uuid}"
	RouteUserGetAllWorkspaces = "/user/{user_uuid}/workspace"
	RouteUserGetAllRoles      = "/user/{user_uuid}/role"

	RouteUserGetOneWorkspaceByName = "/user/{user_uuid}/workspace/name={workspace_name}"
	RouteUserGetOneRoleByName      = "/user/{user_uuid}/workspace/name={workspace_name}/role/name={role_name}"
	RouteUserGetOneRuleByName      = "/user/{user_uuid}/workspace/name={workspace_name}/rule/name={rule_name}"
	RouteUserGetAllRules           = "/user/{user_uuid}/rule"
	RouteUserGetAllUserTokens      = "/user/{user_uuid}/user-token"
	RouteUserAppendWorkspace       = "/workspace/{workspace_uuid}/user/{user_uuid}"
	RouteUserDropWorkspace         = "/workspace/{workspace_uuid}/user/{user_uuid}"
	RouteUserAppendRole            = "/workspace/{workspace_uuid}/role/{role_uuid}/user/{user_uuid}"
	RouteUserDropRole              = "/workspace/{workspace_uuid}/role/{role_uuid}/user/{user_uuid}"
	RouteUserAppendRule            = "/user/{user_uuid}/rule/{rule_uuid}"
	RouteUserDropRule              = "/user/{user_uuid}/rule/{rule_uuid}"
	RouteUserUpdate                = "/user/{user_uuid}"
	RouteUserActivate              = "/user/{user_uuid}/activate"
	RouteUserSuspend               = "/user/{user_uuid}/suspend"
	RouteUserTokenIdentify         = "/identify"
	RouteUserTokenCreateByCreds    = "/authn"
	RouteUserTokenCreateByToken    = "/user/{user_uuid}/user-token"
	RouteUserTokenGetOne           = "/user/{user_uuid}/user-token/{user_token_uuid}"
	RouteUserTokenGetAll           = "/user/{user_uuid}/user-token"
	RouteUserTokenDelete           = "/user/{user_uuid}/user-token/{user_token_uuid}"

	RouteVerification = "/verif"

	RouteWorkspaceInvite         = "/workspace/{workspace_uuid}/invite"
	RouteWorkspaceCreate         = "/workspace"
	RouteWorkspaceGetOne         = "/workspace/{workspace_uuid}"
	RouteWorkspaceGetAll         = "/workspace"
	RouteWorkspaceDelete         = "/workspace/{workspace_uuid}"
	RouteWorkspaceUserGetByEmail = "/workspace/{workspace_uuid}/user/email={user_email}"
	RouteWorkspaceGetUsers       = "/workspace/{workspace_uuid}/user"
	RouteWorkspaceGetAllRoles    = "/workspace/{workspace_uuid}/role"
	RouteWorkspaceGetAllRules    = "/workspace/{workspace_uuid}/rule"
)
